steps:
  - id: "docker-build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}", "."]

  - id: "docker-push"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}"]

  - id: "migration"
    name: "${_IMAGE_NAME}" # プッシュしたNode.jsベースのイメージ
    entrypoint: npx
    args: ["prisma", "migrate", "deploy"]
    env:
      - "DATABASE_URL=mysql://root:${DATABASE_PASS}@${_DATABASE_HOST}:${_DATABASE_PORT}/${DATABASE_NAME}"
    secretEnv:
      - DATABASE_PASS
    dir: prisma # schema.prisma のある場所を指定（プロジェクト構成によっては . に変更）

options:
  pool:
    name: projects/$PROJECT_ID/locations/asia-northeast1/workerPools/shimizu-private-pool
  dynamic_substitutions: true

substitutions:
  _IMAGE_NAME: gcr.io/${PROJECT_ID}/your-nextjs-app
  _DATABASE_HOST: 10.10.1.3
  _DATABASE_PORT: "3306"
  _DATABASE_PASSWORD_KEY: database_password
  DATABASE_NAME: abcmart

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/${_DATABASE_PASSWORD_KEY}/versions/latest
      env: DATABASE_PASS
