steps:
  - id: "docker-build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}", "."]

  - id: "docker-push"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}"]

  # ✅ ステップ①：DBの存在チェック＋なければ作成
  - id: "create-database-if-needed"
    name: "mysql:8.0"
    script: |
      #!/bin/bash
      echo "Checking DB existence..."
      if mysql -h 10.10.1.3 -P 3306 -u root -ppassword -e "SHOW DATABASES LIKE 'abcmart';" | grep abcmart; then
        echo "✅ DB exists"
      else
        echo "❌ Creating DB..."
        mysql -h 10.10.1.3 -P 3306 -u root -ppassword -e "CREATE DATABASE abcmart;"
      fi
    secretEnv:
      - DATABASE_PASS

  - id: "migration"
    name: "${_IMAGE_NAME}" # プッシュしたNode.jsベースのイメージ
    entrypoint: npx
    args: ["prisma", "migrate", "deploy"]
    env:
      - "DATABASE_URL=mysql://root:password@${_DATABASE_HOST}:${_DATABASE_PORT}/${_DATABASE_NAME}"
    secretEnv:
      - DATABASE_PASS
    dir: prisma # schema.prisma のある場所を指定（プロジェクト構成によっては . に変更）

options:
  pool:
    name: projects/$PROJECT_ID/locations/asia-northeast1/workerPools/shimizu-private-pool
  dynamic_substitutions: true

substitutions:
  _IMAGE_NAME: gcr.io/${PROJECT_ID}/your-nextjs-app
  _DATABASE_HOST: 10.10.1.3
  _DATABASE_PORT: "3306"
  _DATABASE_PASSWORD_KEY: database_password
  _DATABASE_NAME: abcmart

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/${_DATABASE_PASSWORD_KEY}/versions/latest
      env: DATABASE_PASS
