# docker-compose.yml
version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql
    ports:
      - "3307:3306"  # 外部から3307でアクセス
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
